name: CI
on:
    push:
        branches:
        - main    

jobs:    
    build:
        name: Checkout code
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: DEPLOY STATIC WEBSITE FROM S3 BUCKET
        #   run: aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
          run: aws s3 sync ./ s3://github-actions-my-static-website-bucket --delete

    